environment:
  name: prod
  project: cdf-bootcamp-28-prod
  validation-type: prod
  selected:
    - modules/bootcamp/data_foundation
    - modules/bootcamp/ice_cream_api
    - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      # Variables shared by modules
      data_foundation:
        data_developer_source_id: 18b3422b-6509-4393-9150-3ff131a8156f
        
      icapi_ds_external_id: ds_icapi
      icapi_space_name: icapi_dm_space
      ice_cream_api:
        icapi_extractors_source_id: 7da1c207-c5ee-47a5-b77b-24044e36e8d7
        tokenUri: ${IDP_TOKEN_URL}
        cdfProjectName: ${CDF_PROJECT}
        scopes: ${IDP_SCOPES}
        icapi_trigger_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_trigger_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
        icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
        icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}



      use_cases:
        oee:
          data_pipeline_oee_source_id: 3421e6b9-3166-4b8a-9a67-8a99dd350357
          uc_oee_ds_external_id: ds_uc_oee
          oee_space_name: oee_ts_space
          data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
          data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
